export const mockHotel = {};
export const mockRooms = [];
export const mockTestimonials = [];
export const mockTrips = [];
export const mockAdminDashboard = {
  stats: {
    total_revenue: 0,
    total_bookings: 0,
    occupancy_rate: 0,
    active_staff: 0,
    open_maintenance: 0,
    new_enquiries: 0,
  },
  revenueSeries: [],
  occupancy: {},
};

/*
export const mockHotel = {
  hotel_name: "Panchavati Grand",
  tagline: "Where Sacred Nashik Meets Luxury",
  address: "Near Ramkund Ghat, Panchavati, Nashik, Maharashtra 422003",
  phone: "+91-0253-4447777",
  email: "stay@panchavatgrand.in",
  gst_percent: 12,
  whatsapp: "919999999999",
};
*/

export const mockRooms = [
  {
    id: 1,
    room_number: "101",
    name: "Godavari Standard",
    category: "Standard",
    description: "Warm, heritage-inspired comfort with temple-quarter charm and all essentials for a restful stay.",
    base_price: 1800,
    pricing: { pricePerNight: 1800, priceType: "base", savings: 0 },
    capacity: 2,
    amenities: ["AC", "WiFi", "TV", "Room Service", "Tea/Coffee Maker"],
    images: ["/assets/images/placeholder-room.svg"],
    floor: 1,
    view_type: "City View",
    bed_type: "Queen",
    size_sqm: 24,
    nashik_landmark: "City view, 5 min walk to Ramkund Ghat",
    available: true,
    availableCount: 2,
    urgencyLabel: "Only 2 rooms left!",
    instantConfirmation: true,
    viewers: 6,
    bookedThisWeek: 4,
  },
  {
    id: 2,
    room_number: "201",
    name: "Panchavati Deluxe",
    category: "Deluxe",
    description: "A balcony room with partial Godavari views, layered textiles, and richer comfort touches.",
    base_price: 3200,
    pricing: { pricePerNight: 2880, priceType: "discounted", savings: 320 },
    capacity: 3,
    amenities: ["AC", "WiFi", "Smart TV", "Rain Shower", "Balcony", "Mini Fridge", "Room Service"],
    images: ["/assets/images/placeholder-room.svg"],
    floor: 2,
    view_type: "Godavari View",
    bed_type: "King",
    size_sqm: 30,
    nashik_landmark: "Godavari River partial view",
    available: true,
    availableCount: 1,
    urgencyLabel: "Only 1 room left!",
    instantConfirmation: true,
    viewers: 10,
    bookedThisWeek: 6,
  },
  {
    id: 3,
    room_number: "301",
    name: "Nashik Family Suite",
    category: "Family",
    description: "A spacious suite for group pilgrimages and family escapes with Sahyadri-facing windows.",
    base_price: 4500,
    pricing: { pricePerNight: 4500, priceType: "base", savings: 0 },
    capacity: 4,
    amenities: ["AC", "WiFi", "2 Smart TVs", "Bathtub", "Dining Area", "Kids Kit"],
    images: ["/assets/images/placeholder-room.svg"],
    floor: 3,
    view_type: "Mountain View",
    bed_type: "King + Twin",
    size_sqm: 46,
    nashik_landmark: "2 connecting rooms, Sahyadri mountain view",
    available: true,
    availableCount: 3,
    urgencyLabel: "Only 3 rooms left!",
    instantConfirmation: true,
    viewers: 8,
    bookedThisWeek: 5,
  },
  {
    id: 4,
    room_number: "401",
    name: "Kumbh Presidential Suite",
    category: "Presidential",
    description: "A top-floor signature suite with panoramic views, private balcony, jacuzzi, and wine hamper.",
    base_price: 9000,
    pricing: { pricePerNight: 9000, priceType: "base", savings: 0 },
    capacity: 2,
    amenities: ["AC", "Ultra-fast WiFi", "OLED Smart TV", "Jacuzzi", "Kitchenette", "Private Balcony"],
    images: ["/assets/images/placeholder-room.svg"],
    floor: 4,
    view_type: "Panoramic View",
    bed_type: "King",
    size_sqm: 72,
    nashik_landmark: "360° view — Godavari + Sahyadri + city panorama",
    available: false,
    availableCount: 0,
    urgencyLabel: null,
    instantConfirmation: false,
    viewers: 12,
    bookedThisWeek: 3,
  },
];

export const mockTestimonials = [
  {
    id: 1,
    cust_name: "Sarah Johnson",
    nationality: "USA",
    room_category: "Family",
    rating: 5,
    comment: "The family suite felt thoughtful and warm, and the team made our Godavari visit seamless.",
  },
  {
    id: 2,
    cust_name: "Aarav Patil",
    nationality: "India",
    room_category: "Deluxe",
    rating: 4,
    comment: "Excellent location for Panchavati and a polished room with an unexpectedly lovely balcony view.",
  },
  {
    id: 3,
    cust_name: "Amina Khan",
    nationality: "UAE",
    room_category: "Presidential",
    rating: 5,
    comment: "The top-floor suite is dramatic in the best way. It feels rooted in Nashik without being themed kitsch.",
  },
];

export const mockTrips = [
  {
    id: 11,
    booking_ref: "PG-2026-00011",
    room_name: "Panchavati Deluxe",
    category: "Deluxe",
    image: "/assets/images/placeholder-room.svg",
    check_in: "2026-04-16",
    check_out: "2026-04-19",
    nights: 3,
    guests: 2,
    total_amount: 10752,
    gst_amount: 1152,
    payment_status: "paid",
    status: "confirmed",
  },
  {
    id: 12,
    booking_ref: "PG-2026-00007",
    room_name: "Nashik Family Suite",
    category: "Family",
    image: "/assets/images/placeholder-room.svg",
    check_in: "2026-03-30",
    check_out: "2026-04-02",
    nights: 3,
    guests: 4,
    total_amount: 15120,
    gst_amount: 1620,
    payment_status: "paid",
    status: "checked_out",
  },
  {
    id: 13,
    booking_ref: "PG-2026-00015",
    room_name: "Panchavati Deluxe",
    category: "Deluxe",
    image: "/assets/images/placeholder-room.svg",
    check_in: "2026-04-13",
    check_out: "2026-04-15",
    nights: 2,
    guests: 2,
    total_amount: 7168,
    gst_amount: 768,
    payment_status: "pay_at_hotel",
    status: "confirmed",
  },
];

export const mockAdminDashboard = {
  stats: {
    total_revenue: 582400,
    total_bookings: 184,
    occupancy_rate: 74,
    active_staff: 18,
    open_maintenance: 6,
    new_enquiries: 12,
  },
  revenueSeries: [
    { month: "2025-11", revenue: 320000, bookings: 88 },
    { month: "2025-12", revenue: 402000, bookings: 109 },
    { month: "2026-01", revenue: 486000, bookings: 131 },
    { month: "2026-02", revenue: 521000, bookings: 140 },
    { month: "2026-03", revenue: 575000, bookings: 162 },
    { month: "2026-04", revenue: 582400, bookings: 184 },
  ],
  occupancy: {
    available: 4,
    occupied: 3,
    cleaning: 2,
    maintenance: 1,
  },
};
